---
title: 'Reproducible Research: Peer Assessment 1'
output:
  html_document: 
    keep_md: yes
    
---

## 1 Loading and preprocessing the data

```{r}
### Set working dir  
setwd("~/R/Data_science_course/Git/RepData_PeerAssessment1")  

### Read provided data file  
data <- read.csv("activity.csv", header = TRUE, sep = ",", na.strings = "NA")  

### Look at the data  
head(data)


### Convert data to date resp. factor format  
data$date <- as.Date(data$date, format = "%Y-%m-%d")  
data$interval <- factor(data$interval)  

### Remove "na"  
data_clean <- data[!is.na(as.character(data$steps)),]  
head(data_clean)
```

## 2 What is mean total number of steps taken per day?  
```{r}
### Creating a data frame with the steps taken for each day  
steps_aggr_day <- aggregate(steps ~ date, data = data_clean, sum)  

### Adding column names to the created data frame  
colnames(steps_aggr_day) <- c("date", "steps")  
hist(as.numeric(steps_aggr_day$steps), breaks = 20, col = "red", xlab = "Number of Steps", main= "Histogram of the total number of steps taken each day")  

```
```{r}
### Mean
mean(steps_aggr_day$steps)  

### Median  
median(steps_aggr_day$steps)

```

## 3 What is the average daily activity pattern?  
```{r}
### Calculating the average  
avg_steps_aggr <- aggregate(data_clean$steps, by=list(interval=data_clean$interval), FUN=mean)  

### Adding columns names  
colnames(avg_steps_aggr) <- c("interval", "average_steps")  

### ploting the average daily activity pattern  
plot(as.integer(levels(avg_steps_aggr$interval)), avg_steps_aggr$average_steps, type="l", xlab = "Interval", ylab = "Avg Number of Steps", main = "Average Daily Activity Pattern",  col ="blue")

### The maximum number of average steps
max_steps <- max(avg_steps_aggr$average_steps)  
max_steps  

### The 5-minute interval that contains the maximum number of steps  
interval_max_steps <- avg_steps_aggr[which.max(avg_steps_aggr$average_steps),]$interval  
interval_max_steps  
```

## 4 Imputing missing values
```{r}
### find missing values steps  
sum(is.na(as.character(data$steps)))  

### find missing values date  
sum(is.na(as.character(data$date)))  

#### find missing values inteval  
sum(is.na(as.character(data$interval)))  

### finding the indices of missing values (NAs)  
missing_values_index <- which(is.na(as.character(data$steps)))  
all_data <- data  

### Imputing missing values using the mean for that 5-minute interval  
all_data[missing_values_index,   ]$steps<-unlist(lapply(missing_values_index,FUN=function(missing_values_index){  
avg_steps_aggr[data[missing_values_index,]$interval==avg_steps_aggr$interval,]$average_steps  
}))  

### Look at the data

summary(all_data)  

steps_each_day_full <- aggregate(steps ~ date, data = all_data, sum)  

### Adding column names to the created data frame  
colnames(steps_each_day_full) <- c("date", "steps")

#### Making the histogram  
hist(as.numeric(steps_each_day_full$steps), breaks = 20, col = "red", xlab = "Number of Steps", main= "Histogram of the total number of steps taken each day")  

### Mean  
mean(steps_each_day_full$steps)  

### Median  
median(steps_each_day_full$steps)    
```
## 5 Are there differences in activity patterns between weekdays and weekends?
```{r}
### Creating a factor variable "day" to store the day of the week  
all_data$day <- as.factor(weekdays(all_data$date))  

### Creating a logical variable "is_weekday" (weekday=TRUE, weekend = FALE) :  
all_data$is_weekday <- ifelse(!(all_data$day %in% c("lördag","söndag")), TRUE, FALSE)  

### Calculating the average number of steps for weekdays  
weekdays_data <- all_data[all_data$is_weekday,]  
steps_per_interval_weekdays <- aggregate(weekdays_data$steps,by=list(interval=weekdays_data$interval), FUN=mean)  

### Calculating the average number of steps for weekends  
weekends_data <- all_data[!all_data$is_weekday,]  
steps_per_interval_weekends <- aggregate(weekends_data$steps, by=list(interval=weekends_data$interval),   FUN=mean)  

###  Adding columns names  
colnames(steps_per_interval_weekdays) <- c("interval", "average_steps")  
colnames(steps_per_interval_weekends) <- c("interval", "average_steps")  

####  Adding a column to indecate the day  
steps_per_interval_weekdays$day <- "Weekday"  
steps_per_interval_weekends$day <- "Weekend"    

### Merging the two datasets  
week_data <- rbind(steps_per_interval_weekends, steps_per_interval_weekdays)  

### Convert day to factor type  
week_data$day <- as.factor(week_data$day)  

### Making the plot  
library(lattice)  
xyplot(average_steps ~  interval | day, data = week_data, layout = c(1,2), type ="l", ylab="Number of Steps")  
```

```{r}
#END OF PROJECT
```



















